### ISSUE TITLE
Is a bind type of write-only possible?

### ISSUE THREAD

**Issue by bugabinga** [kentonv/home-container#3]
Hi!

The `browser-container-launcher.sh` for example mounts `Pictures` as __read-only__. But if we are worried about browser bugs leading to exfiltration of data, even __read-only__ is harmful (making the distinction between __read-only__ and __full__ kind of moot).

**Comment by kentonv** [comment]
Hi Oliver,

If you want to hide files from the browser, you should not map them at all. By default none of your home directory is visible in the container, except for the directories you specify to map in.

A "write-only" mapping in theory could make sense if you wanted to let the browser save downloads to some directory without being able to read any of the existing downloads. However, AFAIK there is no such thing as a write-only bind mapping, so I don't think this is something home-container can implement easily.

**Comment by bugabinga** [comment]
> A "write-only" mapping in theory could make sense if you wanted to let the browser save downloads to some directory without being able to read any of the existing downloads.
> 
This is what I was thinking about. 
> However, AFAIK there is no such thing as a write-only bind mapping, so I don't think this is something home-container can implement easily.
> 
Thank you for explaining.
